export enum EegMarker {
  LEFT_HAND = 'LEFT_HAND',
  RIGHT_HAND = 'RIGHT_HAND',
  BOTH_HANDS = 'BOTH_HANDS',
  FEET = 'FEET',
  REST = 'REST',
  IDLE = 'IDLE',
  SSVEP_9HZ = 'SSVEP_9HZ',
  SSVEP_11HZ = 'SSVEP_11HZ',
  SSVEP_13HZ = 'SSVEP_13HZ',
  SSVEP_15HZ = 'SSVEP_15HZ',
  SSVEP_IDLE = 'SSVEP_IDLE',
}
